# Generated by Django 3.2.4 on 2021-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=32, verbose_name='ユーザー名')),
            ],
        ),
    ]
